const products = [
    // Вермут
    { id: 1, name: 'ВЕРМУТ CINZANO BIANCO 1,0 ЛИТРА', price: 2429, category: 'vermut', inStock: true, image: '/photo/1.jpg' },
    { id: 2, name: 'ВЕРМУТ MARTINI EXTRA DRY белый сухой 0,75 ЛИТРА', price: 2190, category: 'vermut', inStock: true, image: '/photo/2.jpg' },
    { id: 3, name: 'ВЕРМУТ MARTINI FIERO 1 ЛИТРА + Schweppes 1 ЛИТРА', price: 2449, category: 'vermut', inStock: false, image: '/photo/3.jpg' },
    { id: 4, name: 'ВЕРМУТ GANCIA BIANCO 0,5 ЛИТРА', price: 990, category: 'vermut', inStock: true, image: '/photo/4.jpg' },
    { id: 5, name: 'ВЕРМУТ CINZANO BIANCO белое сладкое 0,5 ЛИТРА', price: 1829, category: 'vermut', inStock: true, image: '/photo/5.jpg' },
    { id: 6, name: 'ВЕРМУТ MARTINI BIANCO 0,75 ЛИТРА', price: 2099, category: 'vermut', inStock: true, image: '/photo/6.jpg' },
    // Вино
    { id: 7, name: 'ВИНО COMTE DE MARIAC красное полусладкое 0,7 ЛИТРА', price: 1190, category: 'vino', inStock: true, image: '/photo/7.jpg' },
    { id: 8, name: 'ВИНО C’ERA UNA VOLTA PINOT GRIGIO белое сухое 0,75 ЛИТРА', price: 1549, category: 'vino', inStock: true, image: '/photo/8.jpg' },
    { id: 9, name: 'ВИНО COMTE DE MARIAC белое сухое 0,7 ЛИТРА', price: 1190, category: 'vino', inStock: true, image: '/photo/9.jpg' },
    { id: 10, name: 'ВИНО CHIANTI DOCG красное сухое 0,75 ЛИТРА', price: 1850, category: 'vino', inStock: true, image: '/photo/10.jpg' },
    { id: 11, name: 'ВИНО COMTE DE MARIAC белое полусладкое 0,7 ЛИТРА', price: 1190, category: 'vino', inStock: true, image: '/photo/11.jpg' },
    { id: 12, name: 'ВИНО MANCURA SAUVIGNON BLANC белое сухое 0,75 ЛИТРА', price: 1429, category: 'vino', inStock: true, image: '/photo/12.jpg' },
    { id: 13, name: 'ВИНО VINEDOS SANTA LUCIA SAUVIGNON BLANC белое сухое 0,75 ЛИТРА', price: 1529, category: 'vino', inStock: true, image: '/photo/13.jpg' },
    { id: 14, name: 'ВИНО КИНДЗМАРАУЛИ красное полусладкое 0,75 ЛИТРА', price: 1349, category: 'vino', inStock: true, image: '/photo/14.jpg' },
    { id: 15, name: 'ВИНО Gewurztraminer белое полусладкое 0,75 ЛИТРА', price: 1599, category: 'vino', inStock: true, image: '/photo/15.jpg' },
    { id: 16, name: 'ВИНО MARE ALTA VINHO VERDE белое полусухое 0,7 ЛИТРА', price: 1490, category: 'vino', inStock: true, image: '/photo/16.jpg' },
    { id: 17, name: 'ВИНО MANCURA CABERNET красное сухое 0,75 ЛИТРА', price: 1429, category: 'vino', inStock: false, image: '/photo/17.jpg' },
    { id: 18, name: 'ВИНО COMTE DE MARIAC красное сухое 0,7 ЛИТРА', price: 1190, category: 'vino', inStock: true, image: '/photo/18.jpg' },
    { id: 19, name: 'Вино Кампо Вента Дон Хуан Тиерра де Кастилья белое сухое 0.75 ЛИТРА', price: 1490, category: 'vino', inStock: true, image: '/photo/19.jpg' },
    { id: 20, name: 'ВИНО ИГРИСТОЕ INKERMAN ROSE полусладкое 0,75 ЛИТРА', price: 1490, category: 'vino', inStock: true, image: '/photo/20.jpg' },
    { id: 21, name: 'ВИНО PINOT NOIR красное сухое 0,75 ЛИТРА', price: 1800, category: 'vino', inStock: true, image: '/photo/21.jpg' },
    { id: 22, name: 'ВИНО INKERMAN МУСКАТ белое полусладкое 0,75 ЛИТРА', price: 1390, category: 'vino', inStock: true, image: '/photo/22.jpg' },
    // Виски
    { id: 23, name: 'ВИСКИ BALLANTINE’s 1,0 ЛИТРА', price: 4249, category: 'viski', inStock: true, image: '/photo/23.jpg' },
    { id: 24, name: 'WHITE HORSE 0,5 ЛИТРА', price: 1890, category: 'viski', inStock: true, image: '/photo/24.jpg' },
    { id: 25, name: 'ВИСКИ BELL’S 0,5 ЛИТРА', price: 1890, category: 'viski', inStock: true, image: '/photo/25.jpg' },
    { id: 26, name: 'ВИСКИ WILLIAM LAWSON’S 0,7 ЛИТРА', price: 2429, category: 'viski', inStock: true, image: '/photo/26.jpg' },
    { id: 27, name: 'ВИСКИ BELL’S 1,0 ЛИТРА', price: 2849, category: 'viski', inStock: true, image: '/photo/27.jpg' },
    { id: 28, name: 'ВИСКИ BALLANTINE’s 0,5 ЛИТРА', price: 3249, category: 'viski', inStock: true, image: '/photo/28.jpg' },
    { id: 29, name: 'ВИСКИ JAMESON 0,5 ЛИТРА', price: 2999, category: 'viski', inStock: true, image: '/photo/29.jpg' },
    { id: 30, name: 'ВИСКИ JACK DANIEL’S 0,7 ЛИТРА', price: 4590, category: 'viski', inStock: true, image: '/photo/30.jpg' },
    { id: 31, name: 'ВИСКИ JOHNNIE WALKER RED LABEL 0,5 ЛИТРА', price: 2490, category: 'viski', inStock: true, image: '/photo/31.jpg' },
    { id: 32, name: 'ВИСКИ JIM BEAM 0,5 ЛИТРА', price: 2849, category: 'viski', inStock: true, image: '/photo/32.jpg' },
    { id: 33, name: 'ВИСКИ WILLIAM LAWSON’S 1,0 ЛИТРА', price: 2790, category: 'viski', inStock: true, image: '/photo/33.jpg' },
    { id: 34, name: 'ВИСКИ JAMESON 0,7 ЛИТРА', price: 4290, category: 'viski', inStock: true, image: '/photo/34.jpg' },
    { id: 35, name: 'ВИСКИ JIM BEAM APPLE 0,7 ЛИТРА', price: 4029, category: 'viski', inStock: true, image: '/photo/35.jpg' },
    { id: 36, name: 'ВИСКИ JOHNNIE WALKER RED LABEL 0,7 ЛИТРА', price: 2949, category: 'viski', inStock: true, image: '/photo/36.jpg' },
    { id: 37, name: 'ВИСКИ BELL’s SPICED 0,7 ЛИТРА', price: 2490, category: 'viski', inStock: true, image: '/photo/37.jpg' },
    { id: 38, name: 'ВИСКИ JAMESON 1,0 ЛИТРА', price: 5999, category: 'viski', inStock: true, image: '/photo/38.jpg' },
    // Водка
    { id: 39, name: 'ВОДКА 5 ОЗЕР 0,7 ЛИТРА', price: 1300, category: 'vodka', inStock: true, image: '/photo/39.jpg' },
    { id: 40, name: 'ВОДКА ABSOLUT 0,75 ЛИТРА', price: 3229, category: 'vodka', inStock: true, image: '/photo/40.jpg' },
    { id: 41, name: 'ВОДКА 5 ОЗЕР 0,5 ЛИТРА', price: 929, category: 'vodka', inStock: true, image: '/photo/41.jpg' },
    { id: 42, name: 'ВОДКА ABSOLUT 0.5 ЛИТРА', price: 2599, category: 'vodka', inStock: true, image: '/photo/42.jpg' },
    { id: 43, name: 'ВОДКА РУССКИЙ СТАНДАРТ 0,7 ЛИТРА', price: 1749, category: 'vodka', inStock: true, image: '/photo/43.jpg' },
    { id: 44, name: 'ВОДКА РУССКИЙ СТАНДАРТ 0,5 ЛИТРА', price: 1290, category: 'vodka', inStock: true, image: '/photo/44.jpg' },
    { id: 45, name: 'ВОДКА ЖУРАВЛИ 0,5 ЛИТРА', price: 979, category: 'vodka', inStock: true, image: '/photo/45.jpg' },
    { id: 46, name: 'ВОДКА ЗЕЛЕНАЯ МАРКА 0,5 ЛИТРА', price: 990, category: 'vodka', inStock: true, image: '/photo/46.jpg' },
    { id: 47, name: 'ВОДКА ТАЛКА 0,5 ЛИТРА', price: 949, category: 'vodka', inStock: true, image: '/photo/47.jpg' },
    { id: 48, name: 'ВОДКА NEMIROFF 0,5 ЛИТРА', price: 749, category: 'vodka', inStock: true, image: '/photo/48.jpg' },
    { id: 49, name: 'ВОДКА ХОРТИЦА 0,7 ЛИТРА', price: 1249, category: 'vodka', inStock: true, image: '/photo/49.jpg' },
    { id: 50, name: 'ВОДКА ХОРТИЦА 0,5 ЛИТРА', price: 949, category: 'vodka', inStock: true, image: '/photo/50.jpg' },
    { id: 51, name: 'ВОДКА NEMIROFF ПЕРЕЦ 0,5 ЛИТРА', price: 799, category: 'vodka', inStock: true, image: '/photo/51.jpg' },
    { id: 52, name: 'ВОДКА ЦАРСКАЯ 0,5 ЛИТРА', price: 1249, category: 'vodka', inStock: true, image: '/photo/52.jpg' },
    { id: 53, name: 'ВОДКА ЦАРСКАЯ 0,7 ЛИТРА', price: 1629, category: 'vodka', inStock: true, image: '/photo/53.jpg' },
    { id: 54, name: 'НАСТОЙКА NEMIROFF КЛЮКВА 0,5 ЛИТРА', price: 749, category: 'vodka', inStock: true, image: '/photo/54.jpg' },
    // Джин
    { id: 55, name: 'ДЖИН BEEFEATER 0,7 ЛИТРА', price: 3890, category: 'dzhin', inStock: true, image: '/photo/55.jpg' },
    { id: 56, name: 'ДЖИН GORDON’S 0,7 ЛИТРА', price: 3149, category: 'dzhin', inStock: false, image: '/photo/56.jpg' },
    { id: 57, name: 'ДЖИН TANQUERAY LONDON DRY 1,0 ЛИТРА', price: 3749, category: 'dzhin', inStock: true, image: '/photo/57.jpg' },
    // Коньяк
    { id: 58, name: 'КОНЬЯК СТАРЫЙ КЕНИНГСБЕРГ 4 года 0,5 ЛИТРА', price: 1499, category: 'konyak', inStock: true, image: '/photo/58.jpg' },
    { id: 59, name: 'КОНЬЯК Дару-Бенд 5 лет 0,5 ЛИТРА', price: 1290, category: 'konyak', inStock: true, image: '/photo/59.jpg' },
    { id: 60, name: 'КОНЬЯК DAVID IVERELI 7 лет 0,5 ЛИТРА', price: 1790, category: 'konyak', inStock: false, image: '/photo/60.jpg' },
    { id: 61, name: 'КОНЬЯК КОЧАРИ 3 года 0,5 ЛИТРА', price: 1099, category: 'konyak', inStock: true, image: '/photo/61.jpg' },
    { id: 62, name: 'КОНЬЯК АРАРАТ 3 года 0,5 ЛИТРА', price: 2190, category: 'konyak', inStock: true, image: '/photo/62.jpg' },
    { id: 63, name: 'КОНЬЯК АРАРАТ 3 года 0,7 ЛИТРА', price: 2590, category: 'konyak', inStock: true, image: '/photo/63.jpg' },
    { id: 64, name: 'КОНЬЯК НОЙ 3 ГОДА 0,5 ЛИТРА', price: 1950, category: 'konyak', inStock: true, image: '/photo/64.jpg' },
    { id: 65, name: 'КОНЬЯК A. DE FUSSIGNY SELECTION 0,5 ЛИТРА', price: 2990, category: 'konyak', inStock: true, image: '/photo/65.jpg' },
    { id: 66, name: 'Коньяк Кочари 5 лет 0,5 л', price: 1390, category: 'konyak', inStock: true, image: '/photo/66.jpg' },
    { id: 67, name: 'КОНЬЯК АРАРАТ 5 ЗВЕЗД 0,5 ЛИТРА', price: 2489, category: 'konyak', inStock: true, image: '/photo/67.jpg' },
    { id: 68, name: 'КОНЬЯК АРАРАТ 5 звезд 0,7 ЛИТРА', price: 3090, category: 'konyak', inStock: true, image: '/photo/68.jpg' },
    { id: 69, name: 'КОНЬЯК HENNESSY VS 0,7 ЛИТРА', price: 7990, category: 'konyak', inStock: true, image: '/photo/69.jpg' },
    { id: 70, name: 'КОНЬЯК COURVOISIER VS 0,7 ЛИТРА', price: 8390, category: 'konyak', inStock: true, image: '/photo/70.jpg' },
    { id: 71, name: 'КОНЬЯК HENNESSY VSOP 0,7 ЛИТРА', price: 12990, category: 'konyak', inStock: false, image: '/photo/71.jpg' },
    { id: 72, name: 'КОНЬЯК REMY MARTIN SUPERIEUR VS 0,7 ЛИТРА', price: 9290, category: 'konyak', inStock: true, image: '/photo/72.jpg' },
    { id: 73, name: 'КОНЬЯК COURVOISIER VSOP 0,7 ЛИТРА', price: 9190, category: 'konyak', inStock: true, image: '/photo/73.jpg' },
    // Ликёр
    { id: 74, name: 'ЛИКЕР JAGERMEISTERP 0,7 ЛИТРА', price: 3549, category: 'liker', inStock: true, image: '/photo/74.jpg' },
    { id: 75, name: 'ЛИКЕР ЛИМОНЧЕЛЛО 0,5 ЛИТРА', price: 1249, category: 'liker', inStock: true, image: '/photo/75.jpg' },
    { id: 76, name: 'ЛИКЕР BAILEYS 0,7 ЛИТРА', price: 3149, category: 'liker', inStock: true, image: '/photo/76.jpg' },
    { id: 77, name: 'ЛИКЕР КСУ-КСУ XUXU 0,7 ЛИТРА', price: 1990, category: 'liker', inStock: true, image: '/photo/77.jpg' },
    { id: 78, name: 'Aperol 1,0 ЛИТР', price: 3290, category: 'liker', inStock: true, image: '/photo/78.jpg' },
    { id: 79, name: 'ЛИКЕР SHERIDAN’S 0,5 ЛИТРА', price: 3429, category: 'liker', inStock: true, image: '/photo/79.jpg' },
    { id: 80, name: 'ЛИКЕР SAMBUCA 0,5 ЛИТРА', price: 1549, category: 'liker', inStock: true, image: '/photo/80.jpg' },
    { id: 81, name: 'ЛИКЕР BECHEROVKA 0,7 ЛИТРА', price: 3129, category: 'liker', inStock: true, image: '/photo/81.jpg' },
    { id: 82, name: 'ЛИКЕР COINTREAU 0,7 ЛИТРА', price: 3549, category: 'liker', inStock: true, image: '/photo/82.jpg' },
    // Пиво
    { id: 83, name: 'ПИВО BUD 0,45 ЛИТРА', price: 169, category: 'pivo', inStock: true, image: '/photo/83.jpg' },
    { id: 84, name: 'ПИВО KRUSOVICE 0,5 ЛИТРА', price: 169, category: 'pivo', inStock: true, image: '/photo/84.jpg' },
    { id: 85, name: 'ПИВО ОХОТА КРЕПКОЕ 0,45 ЛИТРА', price: 149, category: 'pivo', inStock: true, image: '/photo/85.jpg' },
    { id: 86, name: 'ПИВО Tuborg green 0,5 ЛИТРА', price: 169, category: 'pivo', inStock: true, image: '/photo/86.jpg' },
    { id: 87, name: 'ПИВО KOZEL СВЕТЛОЕ 0,45 ЛИТРА', price: 169, category: 'pivo', inStock: true, image: '/photo/87.jpg' },
    { id: 88, name: 'ПИВО CORONA EXTRA 0,33 ЛИТРА', price: 289, category: 'pivo', inStock: true, image: '/photo/88.jpg' },
    { id: 89, name: 'ПИВО ШПАТЕН 0,45 ЛИТРА', price: 299, category: 'pivo', inStock: true, image: '/photo/89.jpg' },
    { id: 90, name: 'ПИВО HOEGAARDEN 0,5 ЛИТРА', price: 239, category: 'pivo', inStock: true, image: '/photo/90.jpg' },
    { id: 91, name: 'ПИВO KOZEL ТЕМНОЕ 0,45 ЛИТРА', price: 169, category: 'pivo', inStock: true, image: '/photo/91.jpg' },
    { id: 92, name: 'ПИВО КРОНЕНБУРГ 1664 Blanco 0,5 ЛИТРА', price: 199, category: 'pivo', inStock: true, image: '/photo/92.jpg' },
    { id: 93, name: 'ПИВО MILLER 0,45 ЛИТРА', price: 199, category: 'pivo', inStock: true, image: '/photo/93.jpg' },
    { id: 94, name: 'ПИВО REDD’S яблочный 0,33 ЛИТРА', price: 179, category: 'pivo', inStock: true, image: '/photo/94.jpg' },
    // Ром
    { id: 95, name: 'РОМ CAPITAN MORGAN SPICED GOLD 0,5 ЛИТРА', price: 2190, category: 'rom', inStock: false, image: '/photo/95.jpg' },
    { id: 96, name: 'РОМ BACARDI черный 0,5 ЛИТРА', price: 2599, category: 'rom', inStock: false, image: '/photo/96.jpg' },
    { id: 97, name: 'РОМ BACARDI белый 0,7 ЛИТРА', price: 2999, category: 'rom', inStock: false, image: '/photo/97.jpg' },
    { id: 98, name: 'РОМ BACARDI белый 0,5 ЛИТРА', price: 2499, category: 'rom', inStock: true, image: '/photo/98.jpg' },
    { id: 99, name: 'Barcelo Dorado 0.7', price: 2790, category: 'rom', inStock: true, image: '/photo/99.jpg' },
    { id: 100, name: 'РОМ HAVANA CLUB ANEJO ESPECIAL 3 года 0,7 ЛИТРА', price: 3390, category: 'rom', inStock: true, image: '/photo/100.jpg' },
    { id: 101, name: 'Barcelo Gran Anejo Dark 0.7', price: 2790, category: 'rom', inStock: false, image: '/photo/101.jpg' },
    { id: 102, name: 'РОМ CAPITAN MORGAN WHITE 0,5 ЛИТРА', price: 2190, category: 'rom', inStock: true, image: '/photo/102.jpg' },
    { id: 103, name: 'РОМ CAPITAN MORGAN SPICED GOLD 0,7 ЛИТРА', price: 3900, category: 'rom', inStock: true, image: '/photo/103.jpg' },
    { id: 104, name: 'Barcelo Blanco 0,7 л', price: 2790, category: 'rom', inStock: true, image: '/photo/104.jpg' },
    // Сигареты
    { id: 105, name: 'СИГАРЕТЫ ПАРЛАМЕНТ PARLAMENT АQUA BLUE', price: 450, category: 'sigarety', inStock: true, image: '/photo/105.jpg' },
    { id: 106, name: 'СИГАРЕТЫ MARLBORO с кнопкой', price: 400, category: 'sigarety', inStock: true, image: '/photo/106.jpg' },
    { id: 107, name: 'СИГАРЕТЫ КРАСНЫЕ MARLBORO RED', price: 420, category: 'sigarety', inStock: true, image: '/photo/107.jpg' },
    { id: 108, name: 'СИГАРЕТЫ КЕНТ KENT BLUE FUTURA', price: 400, category: 'sigarety', inStock: true, image: '/photo/108.jpg' },
    { id: 109, name: 'СИГАРЕТЫ КЕНТ KENT NANO SILVER', price: 400, category: 'sigarety', inStock: true, image: '/photo/109.jpg' },
    { id: 110, name: 'СИГАРЕТЫ ВОГ VOGUE MENTHE', price: 360, category: 'sigarety', inStock: true, image: '/photo/110.jpg' },
    { id: 111, name: 'ВОДА КОКА-КОЛА COCA-COLA 2 ЛИТРА', price: 360, category: 'sigarety', inStock: true, image: '/photo/111.jpg' },
    { id: 112, name: 'СИГАРЕТЫ ВИНСТОН WINSTON X-STYLE BLU', price: 360, category: 'sigarety', inStock: true, image: '/photo/112.jpg' },
    { id: 113, name: 'СИГАРЕТЫ ВИНСТОН WINSTON BLUE', price: 360, category: 'sigarety', inStock: true, image: '/photo/113.jpg' },
    { id: 114, name: 'СИГАРЕТЫ КЕНТ KENT SILVER NEO 4', price: 400, category: 'sigarety', inStock: true, image: '/photo/114.jpg' },
    { id: 115, name: 'ВОДА АКВА AQUA MINERALE с газом 0,5 ЛИТРА', price: 120, category: 'sigarety', inStock: true, image: '/photo/115.jpg' },
    { id: 116, name: 'ВОДА BORJOMI 0,5 ЛИТРА', price: 220, category: 'sigarety', inStock: true, image: '/photo/116.jpg' },
    { id: 117, name: 'ВОДА АКВА AQUA MINERALE негаз. 0,5 ЛИТРА', price: 120, category: 'sigarety', inStock: true, image: '/photo/117.jpg' },
    { id: 118, name: 'ВОДА SCHWEPPES INDIAN TONIC 1 ЛИТРА', price: 250, category: 'sigarety', inStock: true, image: '/photo/118.jpg' },
    { id: 119, name: 'ЗАЖИГАЛКА', price: 100, category: 'sigarety', inStock: true, image: '/photo/119.jpg' },
    { id: 120, name: 'СОК RICH Яблоко 1,0 ЛИТРА', price: 350, category: 'sigarety', inStock: true, image: '/photo/120.jpg' },
    // Текила
    { id: 121, name: 'ТЕКИЛА SAUZA BLANCO 0,7 ЛИТРА', price: 2590, category: 'tekila', inStock: true, image: '/photo/121.jpg' },
    { id: 122, name: 'ТЕКИЛА OLMECA GOLD 0,7 ЛИТРА', price: 2890, category: 'tekila', inStock: true, image: '/photo/122.jpg' },
    { id: 123, name: 'ТЕКИЛА JOSE CUERVO ESPECIAL REPOSADO 0,7 ЛИТРА', price: 3190, category: 'tekila', inStock: true, image: '/photo/123.jpg' },
    // Шампанское
    { id: 124, name: 'ШАМПАНСКОЕ ABRAU DURSO BRUT (РОССИЯ) 0,75 ЛИТРА', price: 1290, category: 'shampanskoe', inStock: true, image: '/photo/124.jpg' },
    { id: 125, name: 'ШАМПАНСКОЕ РОССИЙСКОЕ белое полусладкое (РОССИЯ) 0,75 ЛИТРА', price: 790, category: 'shampanskoe', inStock: true, image: '/photo/125.jpg' },
    { id: 126, name: 'Вино игристое Риондо Просекко Фризанте белое сухое 0,75 л', price: 1690, category: 'shampanskoe', inStock: true, image: '/photo/126.jpg' },
    { id: 127, name: 'ШАМПАНСКОЕ Gancia Prosecco (ИТАЛИЯ) 0,7 ЛИТРА', price: 2390, category: 'shampanskoe', inStock: true, image: '/photo/127.jpg' },
    { id: 128, name: 'ВИНО ИГРИСТОЕ INKERMAN ROSE полусладкое 0,75 ЛИТРА', price: 1490, category: 'shampanskoe', inStock: true, image: '/photo/128.jpg' },
    { id: 129, name: 'ШАМПАНСКОЕ ASTI MONDORO DOCG белое сладкое (ИТАЛИЯ) 0,75 ЛИТРА', price: 2390, category: 'shampanskoe', inStock: true, image: '/photo/129.jpg' },
    { id: 130, name: 'ШАМПАНСКОЕ АБРАУ ДЮРСО полусладкое (РОССИЯ) 0,75 ЛИТРА', price: 1149, category: 'shampanskoe', inStock: true, image: '/photo/130.jpg' },
    { id: 131, name: 'ШАМПАНСКОЕ MONDORO BRUT (ИТАЛИЯ) 0,75 ЛИТРА', price: 2390, category: 'shampanskoe', inStock: true, image: '/photo/131.jpg' },
    { id: 132, name: 'ВИНО ИГРИСТОЕ INKERMAN белое сухое 0.,75 ЛИТРА', price: 1490, category: 'shampanskoe', inStock: true, image: '/photo/132.jpg' },
    { id: 133, name: 'ИГРИСТОЕ ВИНО ISSI MALVASIA SPUMANTE белое сладкое 0,75 ЛИТРА', price: 1290, category: 'shampanskoe', inStock: true, image: '/photo/133.jpg' },
    { id: 134, name: 'ШАМПАНСКОЕ MARTINI ASTI (ИТАЛИЯ) 0,75 ЛИТРА', price: 2590, category: 'shampanskoe', inStock: true, image: '/photo/134.jpg' },
    { id: 135, name: 'ВИНО MASSIMO VISCONTI LAMBRUSCO белое сладкое 0,75 ЛИТРА', price: 1099, category: 'shampanskoe', inStock: true, image: '/photo/135.jpg' },
    { id: 136, name: 'ШАМПАНСКОЕ CINZANO PROSECCO белое сухое (ИТАЛИЯ) 0,75 ЛИТРА', price: 2549, category: 'shampanskoe', inStock: true, image: '/photo/136.jpg' },
    { id: 137, name: 'ВИНО ИГРИСТОЕ MASSIMO VISCONTI LAMBRUSCO ROSSO DOLCE красное сладкое 0,75 ЛИТРА', price: 1099, category: 'shampanskoe', inStock: true, image: '/photo/137.jpg' },
    { id: 138, name: 'ШАМПАНСКОЕ BOSCAбелое полу-сладкое (ЛИТВА) 0,75 ЛИТРА', price: 1290, category: 'shampanskoe', inStock: true, image: '/photo/138.jpg' },
    { id: 139, name: 'ШАМПАНСКОЕ ABRAU Light полусладкое (РОССИЯ) 0,75 ЛИТРА', price: 1090, category: 'shampanskoe', inStock: true, image: '/photo/139.jpg' },

];
